version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: chalk
    versions:
    - 4.1.0
